config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'sign-up', to: 'registration#new'
  post 'sign-up', to: 'registration#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "logged in"
      redirect_to root_path
    else
      flash[:notice] = "oh no something went terribly wrong"
      render :new
    end
  end

  def new
    session[:user_id] = current_user
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You're the best thanks for signing up"
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag sign_in_path do |f| %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Sign in" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuthExcersize</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
  <%= flash[:notice] %>
  <% end %>

  <% if current_user %>
  <%= link_to "sign me out", sign_out_path %>
  <% else %>
  <%= link_to "sign me in", sign_in_path %>
  <% end %>






<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<% if current_user %>
  <h3> Current user is: <%= current_user.email %> </h3>
<% else %>

  <h4> Nobody Hurr!!! </h4>

<% end %>